version: "3"

services:
  db: 
    image: postgres
    environment:
      - POSTGRES_DB=dfn080lhvm7tv5
      - POSTGRES_USER=uwfsqxzdxzhuny
      - POSTGRES_PASSWORD=418204f17d7d03c58bdda6ec52bc86a14d61b06aece0d69bf37b5fb9b1ddc509
      - POSTGRES_HOST=ec2-52-44-55-63.compute-1.amazonaws.com
  migration:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/usr/src/project3
    depends_on:
      - db
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/project3
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
