version: "3"

services:
  migration:
    build: .
    command: python3 manage.py migrate
    volumes:
      - .:/usr/src/project3
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/project3
    ports:
      - "8000:8000"
    depends_on:
      - migration
