# Generated by Django 2.0.3 on 2020-04-30 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 30, 5, 7, 53, 745902, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='order',
            name='menuItem',
            field=models.ManyToManyField(blank=True, to='orders.menuItem'),
        ),
    ]
