# Generated by Django 3.0.6 on 2020-06-02 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200602_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 2, 22, 14, 38, 161860, tzinfo=utc)),
        ),
    ]
