# Generated by Django 2.0.3 on 2020-05-07 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200507_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 7, 19, 18, 25, 624321, tzinfo=utc)),
        ),
    ]
