# Generated by Django 2.0.3 on 2020-04-30 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200430_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 30, 5, 12, 32, 150215, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='menuItem',
        ),
        migrations.AddField(
            model_name='order',
            name='menuItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.menuItem'),
        ),
    ]
