# Generated by Django 2.0.3 on 2020-05-07 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200507_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 7, 21, 1, 1, 722514, tzinfo=utc)),
        ),
    ]
