# Generated by Django 3.0.6 on 2020-06-04 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200602_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='section',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 4, 5, 16, 15, 313121, tzinfo=utc)),
        ),
    ]
