# Generated by Django 2.0.3 on 2020-05-05 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200504_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 5, 3, 17, 29, 529520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='orders.Section'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Style'),
        ),
        migrations.AlterField(
            model_name='price',
            name='Topping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='orders.Menu'),
        ),
    ]
