# Generated by Django 2.0.3 on 2020-05-09 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200509_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('menuitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='orders.menuItem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 9, 20, 12, 1, 970478, tzinfo=utc)),
        ),
    ]
