# Generated by Django 2.0.3 on 2020-05-09 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200509_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeprice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sizeprice',
            name='menuitems',
        ),
        migrations.AddField(
            model_name='sizeprice',
            name='menuitem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.menuItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 9, 22, 23, 59, 47268, tzinfo=utc)),
        ),
    ]
