# Generated by Django 2.0.3 on 2020-05-10 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200509_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 0, 6, 26, 958095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Regular', max_length=64),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
