# Generated by Django 2.0.3 on 2020-05-10 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200510_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 10, 22, 57, 28, 376621, tzinfo=utc)),
        ),
    ]
