# Generated by Django 2.0.3 on 2020-05-11 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200510_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 11, 5, 0, 54, 184274, tzinfo=utc)),
        ),
    ]
