# Generated by Django 2.0.3 on 2020-05-13 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200511_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 13, 3, 11, 2, 501096, tzinfo=utc)),
        ),
    ]
